### PR TITLE
v0.3

### PR DESCRIPTION
**Pull request by Ian-Bright**
This branch is meant to hold the changes for v0.3 until complete and ready to merge. Initial commits contain change the logic of the login route to now create a user if they don't already exist in order to accommodate web3auth

### CODE REVIEW

**Comment by hackertron** [comment]
@Ian-Bright  @NicoSerranoP is this PR ready for review ?

**Comment by NicoSerranoP** [comment]
> @Ian-Bright @NicoSerranoP is this PR ready for review ?

Yes 🚀

**Review by hackertron — APPROVED** [review]
approved

**Comment by hackertron** [comment]
@Ian-Bright PR is still marked as draft , I have approved the PR, please change it from draft to ready, when you are ready and then we can merge it.

**Comment by Ian-Bright** [comment]
Thanks @hackertron . Will be ready to merge once we merge the updated frontend into main. Merging this branch now would break the frontend due to old sign-in logic

**Comment by hackertron** [comment]
@Ian-Bright ready for merge/review ?

**Comment by Ian-Bright** [comment]
@hackertron Yessir

**Pull request merged**
